name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mypy flake8 tox

      - name: Run pytest
        run: pytest

      - name: Run mypy
        run: mypy FLASK-TEST

      - name: Run flake8
        run: flake8 FLASK-TEST  

      - name: Run tox
        run: tox
