name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click==7.1.2 Flask==1.1.2 gunicorn==20.0.4 itsdangerous==1.1.0 Jinja2==2.11.3 MarkupSafe==1.1.1 Werkzeug==1.0.1 Flask-Cors vobject pymongo certifi "bson>=0.5.10" pytest mypy flake8 tox

      - name: Run pytest
        run: python -m pytest

      - name: Run mypy
        run: mypy flask-test

      - name: Run flake8
        run: flake8 flask-test

      - name: Run tox
        run: tox

